smtp:
  host: smtp.qq.com # QQ邮箱smtp服务器为 smtp.qq.com
  user: xxxxxxxx@qq.com 
  password: xxxxxxxx # 如果是QQ邮箱，这里填生成的smtp授权码，不是密码
  port: 465 # QQ邮箱端口为465
  ssl: true # QQ邮箱为true
  message:
    from: ZZU自动填报小助手
    to: xxx # 填写一个昵称即可，不重要
    receivers:
    - xxxxxxx@qq.com # 填写你自己的邮箱地址就可以，有多个收件人可以再加
    # - xxxxxx@qq.com

retry:
  times: 3  # 主程序重试次数

crawler:
  headers:
    ua: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4146.4 Safari/537.36 # 伪装为浏览器的请求
  timeout: 21 # 超时时间秒数
  verify: false #ZZU填报网站SSL有些问题，需要关闭SSL验证，否则无法正常请求.
  retry:
    times: 3 # 网络错误重试次数，均失败后抛出错误
  delay:
    min: 1 # 每次请求前随机等待最小秒数
    max: 2 # 每次请求前随机等待最大秒数

zzu:
  username: xxxxxxxxx # 学号
  password: xxxxxxxxxx # 密码

flag:
  profile: 今日您已经填报过了 # 在个人资料界面表示已填报的标志
  submit: 感谢您今日上报 # 填报成功的标志
  resubmit: 你今日的健康状态上报信息已通过审核 # 重复提交的标志
  fail: 提交失败 #填报失败的标志

pattern:
  login_iframe: (?<=iframe name="my_toprr" src=").*?(?=")
  login_url: (?<="POST" action=").*?(?=")
  unknown_key: (?<=input type="hidden" name=").*?(?=")
  unknown_value: (?<=input type="hidden" name=".*?" value=").*?(?=")
  redirect_url: (?<=location=").*?(?=")
  user_profile_url: (?<=id="zzj_top_6s" src=").*?(?=")
  sid: (?<=input type="hidden" name="sid" value=").*?(?=")
  ptopid: (?<=ptopid=).*?(?=&)
  fun18: (?<=input type="hidden" name="fun18" value=").*?(?=")

url:
  base: http://jksb.zzu.edu.cn/
  post: https://jksb.v.zzu.edu.cn/vls6sss/zzujksb.dll/jksb
